name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          rustup default beta
          cargo build --lib --release

      - name: Prepare output
        run: |
          pushd boringtun/src
          zip ../../include.zip wireguard_ffi.h
          popd
          mv target/release/libboringtun.a ./libboringtun-macos12.a
          mv LICENSE.md LICENSE

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos12
          path: |
            include.zip
            libboringtun-macos12.a
            LICENSE

  build-macos-arm64:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build
        run: |
          rustup default beta
          cargo build --lib --release

      - name: Prepare output
        run: mv target/release/libboringtun.a ./libboringtun-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-macos-arm64
          path: libboringtun-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.1.8/aarch64-rpi4-linux-gnu.tar.xz
          tar xf aarch64-rpi4-linux-gnu.tar.xz -C ~

      - name: Configure Rust for RPi
        run: |
          rustup default beta
          cp cargo-config.toml ~/.cargo/config
          rustup target add aarch64-unknown-linux-gnu

      - name: Build RPi
        run: |
          cargo build --lib --release --target aarch64-unknown-linux-gnu
        env:
          TARGET_CC: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-gcc
          TARGET_AR: /home/runner/aarch64-rpi4-linux-gnu/bin/aarch64-rpi4-linux-gnu-ar

      - name: Build linux-x64
        run: |
          cargo build --lib --release

      - name: Rename build output
        run: |
          mv target/aarch64-unknown-linux-gnu/release/libboringtun.a ./libboringtun-rpi-arm64.a
          mv target/release/libboringtun.a ./libboringtun-linux-x64.a

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output-linux
          path: |
            libboringtun-rpi-arm64.a
            libboringtun-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-macos-arm64, build-linux]
    steps:
      - name: Get build output macos12
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos12

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v4
        with:
          name: build-output-macos-arm64

      - name: Get build output linux
        uses: actions/download-artifact@v4
        with:
          name: build-output-linux

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            include.zip
            libboringtun-macos12.a
            libboringtun-macos-arm64.a
            libboringtun-rpi-arm64.a
            libboringtun-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
