name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install beta toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --release

      - name: Prepare output
        run: |
          pushd boringtun/src
          zip ../../include.zip wireguard_ffi.h
          popd
          mv target/release/libboringtun.a ./libboringtun-macos11.a
          mv LICENSE.md LICENSE

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos11
          path: |
            include.zip
            libboringtun-macos11.a
            LICENSE

  build-macos-arm64:
    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install beta toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --lib --release

      - name: Prepare output
        run: mv target/release/libboringtun.a ./libboringtun-macos-arm64.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-macos-arm64
          path: libboringtun-macos-arm64.a

  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.0.8/arm-rpi-linux-gnueabihf.tar.xz
          tar xf arm-rpi-linux-gnueabihf.tar.xz -C ~

      - name: Install beta toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true

      - name: Configure Rust for Android and RPi
        run: |
          ln -sf $ANDROID_NDK_ROOT $ANDROID_SDK_ROOT/ndk-bundle
          cp cargo-config.toml ~/.cargo/config
          rustup target add aarch64-linux-android arm-unknown-linux-gnueabihf

      - name: Build Android
        run: |
          cargo build --lib --release --target aarch64-linux-android
        env:
          TARGET_CC: /usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang
          TARGET_AR: /usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar

      - name: Build RPi
        run: |
          cargo build --lib --release --target arm-unknown-linux-gnueabihf
        env:
          TARGET_CC: /home/runner/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-gcc
          TARGET_AR: /home/runner/arm-rpi-linux-gnueabihf/bin/arm-rpi-linux-gnueabihf-ar

      - name: Build linux-x64
        run: |
          cargo build --lib --release

      - name: Rename build output
        run: |
          mv target/aarch64-linux-android/release/libboringtun.a ./libboringtun-android30.a
          mv target/arm-unknown-linux-gnueabihf/release/libboringtun.a ./libboringtun-rpi.a
          mv target/release/libboringtun.a ./libboringtun-linux-x64.a

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output-linux
          path: |
            libboringtun-android30.a
            libboringtun-rpi.a
            libboringtun-linux-x64.a

  create-release:
    runs-on: ubuntu-22.04
    needs: [build-macos, build-macos-arm64, build-linux]
    steps:
      - name: Get build output macos11
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos11

      - name: Get build output macos-arm64
        uses: actions/download-artifact@v2
        with:
          name: build-output-macos-arm64

      - name: Get build output linux
        uses: actions/download-artifact@v2
        with:
          name: build-output-linux

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            include.zip
            libboringtun-macos11.a
            libboringtun-macos-arm64.a
            libboringtun-android30.a
            libboringtun-rpi.a
            libboringtun-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
